# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-05-05 18:09
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Team',
            fields=[
                ('team_id', models.CharField(max_length=10, primary_key=True, serialize=False)),
                ('bot_id', models.CharField(max_length=12)),
                ('webhook_url', models.URLField()),
                ('app_access_token', models.CharField(max_length=28)),
                ('bot_access_token', models.CharField(max_length=28)),
            ],
        ),
    ]
