# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-05-05 19:03
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='team',
            name='app_access_token',
            field=models.CharField(max_length=128),
        ),
        migrations.AlterField(
            model_name='team',
            name='bot_access_token',
            field=models.CharField(max_length=128),
        ),
    ]
