# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-05-07 16:53
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0002_auto_20170505_1903'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='team',
            name='webhook_url',
        ),
    ]
