# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-06-11 21:41
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0004_sharedchannel'),
    ]

    operations = [
        migrations.CreateModel(
            name='PostedMsg',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.CharField(max_length=18)),
                ('channel', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='website.SharedChannel')),
                ('satellites', models.ManyToManyField(related_name='_postedmsg_satellites_+', to='website.PostedMsg')),
            ],
        ),
    ]
